# Automatically Generated Makefile by EDE.
# For use with: make
#
# DO NOT MODIFY THIS FILE OR YOUR CHANGES MAY BE LOST.
# EDE is the Emacs Development Environment.
# http://cedet.sourceforge.net/ede.shtml
#

top="$(CURDIR)"/
ede_FILES=Project.ede Makefile

VERSION=1.0
DISTDIR=$(top)Solutions-$(VERSION)



all: Chapter1

.PHONY:Chapter1
Chapter1:
	$(MAKE) -C ch1

tags: 
	$(MAKE) -C ch1/ $(MFLAGS) $@

.PHONY: dist

dist:
	rm -rf $(DISTDIR)
	mkdir $(DISTDIR)
	cp $(ede_FILES) $(DISTDIR)
	$(MAKE) -C ch1 $(MFLAGS) DISTDIR=$(DISTDIR)/ch1 dist
	tar -cvzf $(DISTDIR).tar.gz $(DISTDIR)
	rm -rf $(DISTDIR)

Makefile: Project.ede
	@echo Makefile is out of date!  It needs to be regenerated by EDE.
	@echo If you have not modified Project.ede, you can use 'touch' to update the Makefile time stamp.
	@false



# End of Makefile
